[package]
name = "grid-ray"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = ["glam"]
glam = ["ilattice/glam"]

[dependencies]
ilattice = { path = "../ilattice", default-features = false }
